/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    departments: Department;
    universities: University;
    semesters: Semester;
    courses: Course;
    classes: Class;
    students: Student;
    enrollments: Enrollment;
    timetable: Timetable;
    'teacher-salary': TeacherSalary;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    universities: UniversitiesSelect<false> | UniversitiesSelect<true>;
    semesters: SemestersSelect<false> | SemestersSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    timetable: TimetableSelect<false> | TimetableSelect<true>;
    'teacher-salary': TeacherSalarySelect<false> | TeacherSalarySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'coordinator' | 'teacher' | 'student';
  status: 'active' | 'inactive';
  teacherInfo?: {
    department: number | Department;
    designation: 'Permanent' | 'visiting';
    /**
     * e.g., PhD Computer Science, M.Sc Mathematics
     */
    qualification: string;
    joiningDate: string;
  };
  coordinatorInfo?: {
    department: number | Department;
    /**
     * e.g., PhD Computer Science, M.Sc Mathematics
     */
    qualification: string;
    joiningDate: string;
  };
  personalInfo: {
    phone: string;
    dateOfBirth: string;
    gender: 'male' | 'female';
    /**
     * 13 digits (format: 36300-5419772-3)
     */
    cnic: string;
  };
  address: {
    street: string;
    city: string;
    state: string;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manage university departments
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  name: string;
  /**
   * e.g., CS, MATH, PHY
   */
  code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "universities".
 */
export interface University {
  id: number;
  name: string;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage academic semesters for each department
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "semesters".
 */
export interface Semester {
  id: number;
  /**
   * Enter academic session (e.g., Fall 2024)
   */
  session: string;
  semesterNumber: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8';
  /**
   * Select university first
   */
  university: number | University;
  /**
   * Auto-generated from session, semester number, and university
   */
  name: string;
  /**
   * Auto-generated unique code
   */
  code?: string | null;
  /**
   * Select the department (subject) for this semester
   */
  department: number | Department;
  startDate: string;
  endDate: string;
  /**
   * Auto-calculated based on dates
   */
  status: 'upcoming' | 'ongoing' | 'completed';
  /**
   * Check if this is the currently running semester for this department
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  code: string;
  creditHours: number;
  /**
   * Select the department (subject)
   */
  department: number | Department;
  university: number | University;
  /**
   * Semesters filtered by department
   */
  semester?: (number | null) | Semester;
  /**
   * Teachers filtered by department only
   */
  teacher?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage class sections for courses
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  /**
   * Auto-generated from course and section
   */
  title?: string | null;
  section: string;
  university: number | University;
  department: number | Department;
  course?: (number | null) | Course;
  semester?: (number | null) | Semester;
  teacher?: (number | null) | User;
  days: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday')[];
  /**
   * Select time slot (hourly from 8 AM to 5 PM)
   */
  timeSlot:
    | '08:00-09:00'
    | '09:00-10:00'
    | '10:00-11:00'
    | '11:00-12:00'
    | '12:00-13:00'
    | '13:00-14:00'
    | '14:00-15:00'
    | '15:00-16:00'
    | '16:00-17:00'
    | '17:00-18:00';
  maxStudents: number;
  currentStudents?: number | null;
  lectureType: 'theory' | 'lab';
  status: 'scheduled' | 'ongoing' | 'completed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage student academic records
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: number;
  /**
   * Auto-generated: Roll No - Student Name
   */
  displayTitle?: string | null;
  rollNo: string;
  university: number | University;
  department?: (number | null) | Department;
  semester: number | Semester;
  batch: string;
  admissionDate: string;
  /**
   * Link to student account (personal info will come from Users)
   */
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage student enrollments in class sections
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  /**
   * Select university first to filter students and classes
   */
  university: number | University;
  /**
   * Select department to filter students and classes
   */
  department?: (number | null) | Department;
  semester?: (number | null) | Semester;
  /**
   * Students filtered by university, department & semester
   */
  student?: (number | null) | Student;
  /**
   * Classes filtered by university, department & semester
   */
  class?: (number | null) | Class;
  status: 'enrolled' | 'dropped' | 'completed';
  updatedAt: string;
  createdAt: string;
}
/**
 * Complete timetable - View by class OR by teacher
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timetable".
 */
export interface Timetable {
  id: number;
  /**
   * Auto-generated: Class - Subject - Teacher
   */
  displayTitle?: string | null;
  university: number | University;
  department?: (number | null) | Department;
  semester?: (number | null) | Semester;
  /**
   * Select class (e.g., CS101 Section A)
   */
  class: number | Class;
  /**
   * Select teacher
   */
  teacher: number | User;
  subject: number | Course;
  day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday';
  timeSlot:
    | '08:00-09:00'
    | '09:00-10:00'
    | '10:00-11:00'
    | '11:00-12:00'
    | '12:00-13:00'
    | '13:00-14:00'
    | '14:00-15:00'
    | '15:00-16:00'
    | '16:00-17:00';
  room: string;
  lectureType: 'theory' | 'lab' | 'tutorial';
  status: 'active' | 'cancelled' | 'holiday';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teacher-salary".
 */
export interface TeacherSalary {
  id: number;
  displayTitle?: string | null;
  teacher: number | User;
  /**
   * Select teacher category
   */
  teacherType: 'permanent' | 'visiting';
  /**
   * Monthly fixed salary for permanent teacher
   */
  fixedSalary?: number | null;
  /**
   * Rate per lecture/class
   */
  perClassRate?: number | null;
  /**
   * Extra bonus for this month
   */
  bonus?: number | null;
  /**
   * Fixed deductions for permanent teachers
   */
  deductions?: {
    tax?: number | null;
    otherDeduction?: number | null;
  };
  effectiveFrom: string;
  status?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'universities';
        value: number | University;
      } | null)
    | ({
        relationTo: 'semesters';
        value: number | Semester;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'students';
        value: number | Student;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'timetable';
        value: number | Timetable;
      } | null)
    | ({
        relationTo: 'teacher-salary';
        value: number | TeacherSalary;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  teacherInfo?:
    | T
    | {
        department?: T;
        designation?: T;
        qualification?: T;
        joiningDate?: T;
      };
  coordinatorInfo?:
    | T
    | {
        department?: T;
        qualification?: T;
        joiningDate?: T;
      };
  personalInfo?:
    | T
    | {
        phone?: T;
        dateOfBirth?: T;
        gender?: T;
        cnic?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "universities_select".
 */
export interface UniversitiesSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "semesters_select".
 */
export interface SemestersSelect<T extends boolean = true> {
  session?: T;
  semesterNumber?: T;
  university?: T;
  name?: T;
  code?: T;
  department?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  code?: T;
  creditHours?: T;
  department?: T;
  university?: T;
  semester?: T;
  teacher?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  title?: T;
  section?: T;
  university?: T;
  department?: T;
  course?: T;
  semester?: T;
  teacher?: T;
  days?: T;
  timeSlot?: T;
  maxStudents?: T;
  currentStudents?: T;
  lectureType?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  displayTitle?: T;
  rollNo?: T;
  university?: T;
  department?: T;
  semester?: T;
  batch?: T;
  admissionDate?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  university?: T;
  department?: T;
  semester?: T;
  student?: T;
  class?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timetable_select".
 */
export interface TimetableSelect<T extends boolean = true> {
  displayTitle?: T;
  university?: T;
  department?: T;
  semester?: T;
  class?: T;
  teacher?: T;
  subject?: T;
  day?: T;
  timeSlot?: T;
  room?: T;
  lectureType?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teacher-salary_select".
 */
export interface TeacherSalarySelect<T extends boolean = true> {
  displayTitle?: T;
  teacher?: T;
  teacherType?: T;
  fixedSalary?: T;
  perClassRate?: T;
  bonus?: T;
  deductions?:
    | T
    | {
        tax?: T;
        otherDeduction?: T;
      };
  effectiveFrom?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}